# yaml-language-server: $schema=https://eksctl.io/usage/schema.json
# Full config reference: https://eksctl.io/usage/schema

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-example
  region: us-east-2
  version: "1.29"

managedNodeGroups:
  - name: spot
    instanceTypes:
      - r7i.large
      - r7a.large
      - r6i.large
      - r6a.large
    spot: true
    desiredCapacity: 1
    minSize: 1
    maxSize: 10

addons:
  - name: aws-ebs-csi-driver
    version: latest
  - name: coredns
    version: latest
  - name: eks-pod-identity-agent
    version: latest
  - name: kube-proxy
    version: latest
  - name: vpc-cni
    version: latest

gitops:
  flux:
    gitProvider: github
    flags:
      owner: e-gineering
      repository: eks-example
      branch: main
      namespace: flux-system
      path: flux

cloudWatch:
  clusterLogging:
    enableTypes:
      - all

# Example of using an existing VPC:
# https://github.com/eksctl-io/eksctl/blob/main/examples/04-existing-vpc.yaml
# vpc:
#   id: vpc-0a1b2c3d4e5f6g7h8
#   clusterEndpoints:
#     publicAccess: false
#     privateAccess: true
#   subnets:
#     private:
#       us-east-2a:
#         id: subnet-0a1b2c3d4e5f6g7h8
#       us-east-2b:
#         id: subnet-a0b1c2d3e4f5g6h7f
#       us-east-2c:
#         id: subnet-b0c1d2e3f4g5h63d1

iam:
  # Example of setting up Pod Identity Associations:
  # https://github.com/eksctl-io/eksctl/blob/main/examples/39-pod-identity-association.yaml
  podIdentityAssociations:
    - serviceAccountName: external-secrets
      namespace: kube-system
      # https://external-secrets.io/latest/provider/aws-parameter-store/#iam-policy
      permissionPolicy:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - ssm:GetParameter*
            Resource: "*"

    - serviceAccountName: cluster-autoscaler
      namespace: kube-system
      wellKnownPolicies:
        autoScaler: true

    - serviceAccountName: aws-load-balancer-controller
      namespace: kube-system
      wellKnownPolicies:
        awsLoadBalancerController: true
