# yaml-language-server: $schema=https://eksctl.io/usage/schema.json
# Full config reference: https://eksctl.io/usage/schema

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-example
  region: us-east-2
  version: "1.29"

managedNodeGroups:
  - name: spot
    instanceTypes:
      - r7i.large
      - r7a.large
      - r6i.large
      - r6a.large
    spot: true
    desiredCapacity: 1
    minSize: 1
    maxSize: 10

addons:
  - name: coredns
    version: latest
  - name: kube-proxy
    version: latest
  - name: vpc-cni
    version: latest

# gitops:
#   flux:
#     gitProvider: github
#     flags:
#       owner: e-gineering
#       repository: eks-example
#       branch: main
#       namespace: flux-system
#       path: flux/init
