# yaml-language-server: $schema=https://eksctl.io/usage/schema.json
# Full config reference: https://eksctl.io/usage/schema

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-example
  region: us-east-2

managedNodeGroups:
  - name: spot
    instanceTypes:
      - r7i.large
      - r7a.large
      - r6i.large
      - r6a.large
    spot: true
