apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: widget-express
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ParameterStore
    kind: SecretStore
  target:
    name: widget-express
  dataFrom:
    - find:
        name:
          regexp: dev/widget-express
